#!/bin/sh


case $1 in
	configure)
		n4d-modules enable-plugin /etc/n4d/conf.d/EpoptesVariables.json || true		
		n4d-modules enable-plugin /etc/n4d/conf.d/EpoptesServer.json || true		

	;;
	*)
		echo "Nothing to do"
		;;
esac

#DEBHELPER#
